baseurl: /alonso-gallego-honey

#theme: jekyll-theme-architect
# outros temas aqui: https://github.com/pages-themes

title: QUESTIONÁRIO ALONSO-GALLEGO-HONEY
description: sobre estilos de aprendizagem

desenvolvedor: Prof. Dr. Luiz T. F. Eleno
devurl: https://www.demar.eel.usp.br/docentes/luiz-tadeu-fernandes-eleno.html
