baseurl: /alonso-gallego-honey

theme: jekyll-theme-hacker
#outros temas aqui: https://github.com/pages-themes

title: QUESTIONÁRIO HONEY-ALONSO
description: de estilos de aprendizagem

desenvolvedor: Prof. Dr. Luiz T. F. Eleno
devurl: https://www.demar.eel.usp.br/docentes/luiz-tadeu-fernandes-eleno.html
